#database
spring:
  datasource:
    url: jdbc:p6spy:mysql://192.168.1.101:3306/en_exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  servlet:
     multipart:
        max-file-size: 5MB
        
       

mybatis:
  mapperLocations: classpath:mapper/*.xml
  

#文件保存位置   imagesPath和imagesFilePath路径要保持一致
user:
   imagesPath: file:C:/Users/Qin/Desktop/图片位置/
   imagesFilePath: C:/Users/Qin/Desktop/图片位置/
  
#security:
#   basic:
#      enabled: false
  
  
  
#server:
#  servlet:
#   context-path: /example  