#database
spring:
  datasource:
    url: jdbc:p6spy:mysql://192.168.1.102:3306/en_exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    

mybatis:
  mapperLocations: classpath:mapper/*.xml
  
#security:
#   basic:
#      enabled: false
  
  
  
#server:
#  servlet:
#   context-path: /example  